---
# tasks file for integration
- name: Install the wildcard tls certs
  k8s:
    state: present
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: router-certs
        namespace: openshift-ingress
      data:
        tls.crt: >-
            {{ lookup('file', './' + cluster_name + '/files/api.' + cluster_name + '.' + domain_name + '_fullchain.pem', rstrip=False) | string | b64encode }}
        tls.key: >-
            {{ lookup('file', './' + cluster_name + '/files/api.' + cluster_name + '.' + domain_name + '.key', rstrip=False)  | string | b64encode  }}
      type: kubernetes.io/tls

- name: Patch the Ingress operator to use the certs
  k8s:
    state: present
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        defaultCertificate:
          name: router-certs

- name: Install the api certificates
  k8s:
    state: present
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: api-certs
        namespace: openshift-config
      data:
        tls.crt: >-
            {{ lookup('file', './' + cluster_name + '/files/api.' + cluster_name + '.' + domain_name + '_fullchain.pem', rstrip=False) | string | b64encode }}
        tls.key: >-
            {{ lookup('file', './' + cluster_name + '/files/api.' + cluster_name + '.' + domain_name + '.key', rstrip=False)  | string | b64encode  }}
      type: kubernetes.io/tls

- name: Patch the API server cluster to use the certs
  k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: APIServer
      metadata:
        name: cluster
      spec:
        servingCerts:
          namedCertificates:
          - names:
            - api.{{ cluster_name }}.{{ domain_name }}
            servingCertificate:
              name: api-certs
